project:
  name: Secrover
domains:
  - secrover.xstar97.com
repos:
  - url: https://github.com/xstar97/cluster.git
    branch: main
    description: Talos Kubernetes Cluster
  - url: https://github.com/xstar97/cluster-scripts.git
    branch: main
    description: Cluster Scripts
  - url: https://github.com/xstar97/rompatcherjs.git
    branch: main
    description: RomPatcher.js
  - url: https://github.com/xstar97/apod.git
    branch: main
    description: APOD project
  - url: https://github.com/xstar97/go-littlelinks-generator.git
    branch: main
    description: GO LittleLinks Generator
